services:
  - type: web
    name: dstv-kenya-backend
    env: node
    region: singapore # or your preferred region
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MOBITECH_API_KEY
        sync: false
      - key: MOBITECH_SENDER_NAME
        value: MOBI-TECH
      - key: ADMIN_PHONE_NUMBER
        sync: false
